import { MenuItem } from './types';

export const MENU_ITEMS: MenuItem[] = [
  {
    id: 'd001',
    name: 'อเมริกาโน่',
    description: 'กาแฟดำสกัดสดชื่น',
    price: 65,
    category: 'เครื่องดื่ม',
    imageUrl: 'https://picsum.photos/id/1060/400/400',
    temperatureOptions: ['ร้อน', 'เย็น'],
    sweetnessOptions: ['ไม่หวาน', 'หวานน้อย (25%)', 'ปกติ (50%)', 'หวานมาก (100%)'],
  },
  {
    id: 'd002',
    name: 'คาปูชิโน่',
    description: 'ฟองนมนุ่มละมุนลิ้น',
    price: 70,
    category: 'เครื่องดื่ม',
    imageUrl: 'https://picsum.photos/id/30/400/400',
    temperatureOptions: ['ร้อน', 'เย็น'],
    sweetnessOptions: ['ไม่หวาน', 'หวานน้อย (25%)', 'ปกติ (50%)'],
  },
  {
    id: 'd003',
    name: 'ชาเขียวมัทฉะลาเต้',
    description: 'มัทฉะแท้จากญี่ปุ่น',
    price: 80,
    category: 'เครื่องดื่ม',
    imageUrl: 'https://picsum.photos/id/431/400/400',
    temperatureOptions: ['ร้อน', 'เย็น'],
    sweetnessOptions: ['ไม่หวาน', 'หวานน้อย (25%)', 'ปกติ (50%)', 'หวานมาก (100%)'],
  },
  {
    id: 'd004',
    name: 'ช็อคโกแลต',
    description: 'เข้มข้นถึงใจคนรักช็อคโกแลต',
    price: 75,
    category: 'เครื่องดื่ม',
    imageUrl: 'https://picsum.photos/id/103/400/400',
    temperatureOptions: ['ร้อน', 'เย็น'],
    sweetnessOptions: ['ไม่หวาน', 'หวานน้อย (25%)', 'ปกติ (50%)'],
  },
  {
    id: 's001',
    name: 'ครัวซองต์เนยสด',
    description: 'อบใหม่ทุกวัน หอมกรุ่น',
    price: 90,
    category: 'ของหวาน',
    imageUrl: 'https://picsum.photos/id/292/400/400',
  },
  {
    id: 's002',
    name: 'บราวนี่ชีสเค้ก',
    description: 'ความลงตัวของช็อคโกแลตและชีส',
    price: 120,
    category: 'ของหวาน',
    imageUrl: 'https://picsum.photos/id/367/400/400',
  },
  {
    id: 's003',
    name: 'เค้กแครอท',
    description: 'เนื้อนุ่ม หวานกำลังดี',
    price: 110,
    category: 'ของหวาน',
    imageUrl: 'https://picsum.photos/id/326/400/400',
  },
  {
    id: 's004',
    name: 'มาการองรวมรส',
    description: 'สีสันสดใส หลากรสชาติ',
    price: 150,
    category: 'ของหวาน',
    imageUrl: 'https://picsum.photos/id/435/400/400',
  },
];